version: '3.8'

services: 
    localstack:
        image: localstack/localstack:latest
        environment: 
            - AWS_DEFAULT_REGION=ap-northeast-2
            - EDGE_PORT=4566
            - SERVICES=sqs
        ports: 
            - '4566:4566'
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker:sock"
        networks: 
            - default
            - my_net
    redis:
        image: redis:6.0.5
        command: redis-server --port 6379
        container_name: redis6379
        hostname: redis6379
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379
        networks: 
            - default
            - my_net
networks: 
    my_net:
        driver: bridge
        